name: Sync to GitLab
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: kulla/sync-to-gitlab@v1
        with:
          repository_name: rsbuild-react-starter-template
          owner: stephan_kulla
          token: ${{ secrets.GITLAB_TOKEN }}
